name: .NET CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourStrong@Passw0rd
        ports:
          - 1433:1433
        options: >-
          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong@Passw0rd' -Q 'SELECT 1'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Install EF tools
      run: dotnet tool install --global dotnet-ef

    - name: Run migrations
      run: dotnet ef database update
      env:
        ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=TaskDatabase;User Id=SA;Password=YourStrong@Passw0rd;TrustServerCertificate=true;Encrypt=true;"

    # Uncomment when tests are added
    # - name: Test
    #   run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-api
        path: ./publish